RED_LED_PIN = 32
YELLOW_LED1_PIN = 37
YELLOW_LED2_PIN = 38
GREEN_LED_PIN = 27

ENCODER_PIN = 29
BUTTON_PIN = 8

LEFT_MOTOR_EN_PIN = 13
RIGHT_MOTOR_EN_PIN = 11
LEFT_MOTOR_DIR_PIN1 = 23
LEFT_MOTOR_DIR_PIN2 = 21
RIGHT_MOTOR_DIR_PIN1 = 15
RIGHT_MOTOR_DIR_PIN2 = 19

FRONT_DIST_SENSOR_PIN = 12
LEFT_DIST_SENSOR_PIN = 36
RIGHT_DIST_SENSOR_PIN = 10
BACK_DIST_SENSOR_PIN = 40

FRONT_DIST_SENSOR_BUS = 4
LEFT_DIST_SENSOR_BUS = 6
RIGHT_DIST_SENSOR_BUS = 5
BACK_DIST_SENSOR_BUS = 3

FRONT_DIST_SENSOR_ADDR = 0x2B
BACK_DIST_SENSOR_ADDR = 0x2E
RIGHT_DIST_SENSOR_ADDR = 0x2F
LEFT_DIST_SENSOR_ADDR = 0x2A

FRONT_DIST_SENSOR_OFFSET = -15
BACK_DIST_SENSOR_OFFSET = 0
RIGHT_DIST_SENSOR_OFFSET = -30
LEFT_DIST_SENSOR_OFFSET = -28

