ENCODER_PIN = 29

LEFT_MOTOR_EN_PIN = 13
RIGHT_MOTOR_EN_PIN = 11
LEFT_MOTOR_DIR_PIN1 = 23
LEFT_MOTOR_DIR_PIN2 = 21
RIGHT_MOTOR_DIR_PIN1 = 15
RIGHT_MOTOR_DIR_PIN2 = 19

FRONT_DIST_SENSOR_PIN = 12
FRONT_RIGHT_DIST_SENSOR_PIN = 8
FRONT_LEFT_DIST_SENSOR_PIN = 38
LEFT_DIST_SENSOR_PIN = 36
RIGHT_DIST_SENSOR_PIN = 10
BACK_DIST_SENSOR_PIN = 40
